### PR TITLE
Update master branch after Yarp latest release

### PR DESCRIPTION
**Pull request by gabrielenava**
as suggested by @lrapetti in https://github.com/robotology/icub-gazebo-wholebody/issues/21#issuecomment-507232914:

>@gabrielenava 
>following https://github.com/robotology/QA/issues/358, I think we can think of merging the `devel` into >`master`.

### CODE REVIEW

**Comment by gabrielenava** [comment]
Before merging: @Yeshasvitvs which branch of the repo are you using? is `devel` branch ok for your standup experiments? I remember that I moved to `iCubGazeboV2_5` model for the `standup`, see https://github.com/robotology/icub-gazebo-wholebody/issues/22.

Maybe have a look at the `devel` branch before we merge.

**Comment by gabrielenava** [comment]
ping @Yeshasvitvs

**Comment by yeshasvitirupachuri** [comment]
I am still using old gazebo model for standup experiments. I am using a branch that is based on devel branch.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@gabrielenava There is anything specific blocking this PR? Sorry but back in July I was not completly focused on GitHub. : )

**Comment by gabrielenava** [comment]
>@gabrielenava There is anything specific blocking this PR? Sorry but back in July I was not completly focused on GitHub. : )

I actually also did not see @Yeshasvitvs response. No, there is nothing blocking this PR, I will merge it.

**Pull request merged**
